#!/usr/bin/env bash
# setup.sh — dijalankan di server oleh 'make install'.
# Usage: bash setup.sh <DNS_ADDR> <HTTP_ADDR>
set -e

REMOTE_DIR=/opt/rpzd
DB_USER=dnsrpz
DB_NAME=dnsrpz
DNS_ADDR="${1:-0.0.0.0:53}"
HTTP_ADDR="${2:-0.0.0.0:8080}"

echo "==> [1/4] Setup database PostgreSQL..."
DB_PASS=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
ADMIN_PASS=$(openssl rand -base64 18 | tr -d '/+=' | head -c 20)

if ! su - postgres -c "psql -tAc \"SELECT 1 FROM pg_roles WHERE rolname='$DB_USER'\"" | grep -q 1; then
    su - postgres -c "psql -c \"CREATE ROLE $DB_USER WITH LOGIN PASSWORD '$DB_PASS';\""
    echo "    Role '$DB_USER' dibuat."
else
    su - postgres -c "psql -c \"ALTER ROLE $DB_USER WITH PASSWORD '$DB_PASS';\""
    echo "    Role '$DB_USER' sudah ada, password di-reset."
fi

if ! su - postgres -c "psql -tAc \"SELECT 1 FROM pg_database WHERE datname='$DB_NAME'\"" | grep -q 1; then
    su - postgres -c "psql -c \"CREATE DATABASE $DB_NAME OWNER $DB_USER;\""
    echo "    Database '$DB_NAME' dibuat."
else
    echo "    Database '$DB_NAME' sudah ada."
fi

su - postgres -c "psql -d $DB_NAME -c \"GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;\""
su - postgres -c "psql -d $DB_NAME -c \"GRANT ALL ON SCHEMA public TO $DB_USER;\""
echo "    Privileges granted."

echo "==> [2/4] Generate TLS certificate..."
CERT_DIR=$REMOTE_DIR/certs
mkdir -p "$CERT_DIR"
if [ ! -f "$CERT_DIR/server.crt" ]; then
    SERVER_IP=$(hostname -I | awk '{print $1}')
    openssl req -x509 -newkey rsa:2048 -nodes \
        -keyout "$CERT_DIR/server.key" \
        -out    "$CERT_DIR/server.crt" \
        -days 3650 \
        -subj "/CN=rpzd" \
        -addext "subjectAltName=IP:$SERVER_IP,DNS:localhost" 2>/dev/null
    chmod 600 "$CERT_DIR/server.key"
    echo "    Self-signed cert generated (10 tahun, IP=$SERVER_IP)."
else
    echo "    Cert sudah ada, skip."
fi

echo "==> [3/4] Generate rpzd.conf..."
CONF=$REMOTE_DIR/rpzd.conf
[ -f "$CONF" ] && cp "$CONF" "$CONF.bak" && echo "    Backup config lama -> rpzd.conf.bak"

cat > "$CONF" << 'EOF'
# rpzd config — generated by 'make install'

DATABASE_DSN=postgres://DB_USER_PH:DB_PASS_PH@localhost:5432/DB_NAME_PH
DATABASE_MAX_CONNS=20
DATABASE_MIN_CONNS=2

DNS_ADDRESS=DNS_ADDR_PH
HTTP_ADDRESS=HTTP_ADDR_PH

TLS_CERT_FILE=./certs/server.crt
TLS_KEY_FILE=./certs/server.key

LOG_LEVEL=info

# Admin initial password — used only once on first run, ignored after that.
# You can remove this line after the first successful start.
ADMIN_INIT_PASSWORD=ADMIN_PASS_PH

# Trust Network
# NODE_ROLE: genesis (node pertama), master, atau slave (default)
NODE_ROLE=slave
#NODE_KEY_PATH=./node.key
#NODE_BOOTSTRAP_IP=
EOF

sed -i \
    -e "s|DB_USER_PH|$DB_USER|g" \
    -e "s|DB_PASS_PH|$DB_PASS|g" \
    -e "s|DB_NAME_PH|$DB_NAME|g" \
    -e "s|DNS_ADDR_PH|$DNS_ADDR|g" \
    -e "s|HTTP_ADDR_PH|$HTTP_ADDR|g" \
    -e "s|ADMIN_PASS_PH|$ADMIN_PASS|g" \
    "$CONF"

chmod 600 "$CONF"
echo "    rpzd.conf berhasil dibuat."

echo "==> [4/4] Enable + start systemd services..."
systemctl daemon-reload
systemctl enable rpzd rpzd-dashboard
systemctl restart rpzd rpzd-dashboard
sleep 5
journalctl -u rpzd -u rpzd-dashboard --no-pager -n 20

HTTP_PORT=$(echo "$HTTP_ADDR" | cut -d: -f2)
SERVER_IP=$(hostname -I | awk '{print $1}')
echo ""
echo "========================================================"
echo "  Install selesai!"
echo ""
echo "  Dashboard : https://$SERVER_IP:$HTTP_PORT"
echo ""
echo "  Login pertama:"
echo "    Username  : admin"
echo "    Password  : $ADMIN_PASS"
echo ""
echo "  DSN (simpan baik-baik):"
echo "    postgres://$DB_USER:$DB_PASS@localhost:5432/$DB_NAME"
echo "========================================================"
